//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Log
    {
        public int ID { get; set; }
        public string mobile { get; set; }
        public string ErrCode { get; set; }
        public string ErrMsg { get; set; }
        public System.DateTime Date { get; set; }
        public string Msg { get; set; }
        public string Mid { get; set; }
        public string SMSTitle { get; set; }
        public Nullable<int> scanCount { get; set; }
        public string Url { get; set; }
    }
}
