//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_sms
    {
        public int ID { get; set; }
        public string mobile { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Mid { get; set; }
        public string SMSTitle { get; set; }
        public int scanCount { get; set; }
        public Nullable<bool> st { get; set; }
        public string Url { get; set; }
    }
}
