//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_sms
    {
        public int ID { get; set; }
        public string mobile { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string Mid { get; set; }
        public string SMSTitle { get; set; }
        public int scanCount { get; set; }
        public Nullable<bool> st { get; set; }
        public string Url { get; set; }
    }
}
