//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerExtend
    {
        public int ID { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<double> CusTerm { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalCon { get; set; }
        public byte CusKind { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string Mid { get; set; }
        public Nullable<byte> Defer { get; set; }
        public Nullable<byte> SendInterFace { get; set; }
        public string Bak { get; set; }
        public string WasteBook { get; set; }
        public Nullable<int> BargainID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<byte> EnFlag { get; set; }
        public Nullable<byte> CusSendAttribute { get; set; }
        public Nullable<byte> SendRank { get; set; }
        public byte[] NewVersion { get; set; }
        public Nullable<System.Guid> ExtendID { get; set; }
    }
}
