//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBase
    {
        public int CustomerID { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string PostNumber { get; set; }
        public string Fax { get; set; }
        public Nullable<byte> SendInterFace { get; set; }
        public string Bak { get; set; }
        public string WasteBook { get; set; }
        public Nullable<int> BargainID { get; set; }
        public Nullable<int> Province { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> SendintFlag { get; set; }
        public Nullable<int> FetionFriendStatus { get; set; }
        public string Appsecret { get; set; }
        public string FetionUID { get; set; }
        public Nullable<int> FetionCardId { get; set; }
        public Nullable<int> ProductLine { get; set; }
        public int FetionBuddyCount { get; set; }
        public Nullable<System.DateTime> FetionFriendDate { get; set; }
        public string WeixinId { get; set; }
        public string MobileProvince { get; set; }
        public string MobileCity { get; set; }
        public string Password { get; set; }
        public Nullable<int> Salt { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    }
}
