//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gp
    {
        public int ID { get; set; }
        public string Tel { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<decimal> ProductSum { get; set; }
        public Nullable<int> ProductKind { get; set; }
        public string SendTime { get; set; }
    
        public virtual Market Market { get; set; }
    }
}
