//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Gps = new HashSet<Gp>();
        }
    
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public Nullable<byte> MarketType { get; set; }
        public Nullable<byte> FlatType { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SMName { get; set; }
    
        public virtual ICollection<Gp> Gps { get; set; }
    }
}
