//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public Market()
        {
            this.Gps = new HashSet<Gp>();
        }
    
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public Nullable<byte> MarketType { get; set; }
        public Nullable<byte> FlatType { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SMName { get; set; }
    
        public virtual ICollection<Gp> Gps { get; set; }
    }
}
