//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public Nullable<int> MarketID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string LPrice { get; set; }
        public string HPrice { get; set; }
        public string APrice { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Water { get; set; }
        public string NewPrice { get; set; }
        public string Storehouse { get; set; }
        public string StrikeBargain { get; set; }
        public string Stock { get; set; }
        public string SpecialL { get; set; }
        public string SpecialH { get; set; }
        public string PriceChange { get; set; }
    }
}
