//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideSm
    {
        public int ID { get; set; }
        public string Tel { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> SendInt { get; set; }
        public string Mid { get; set; }
        public string SMSTitle { get; set; }
        public Nullable<byte> Recheck { get; set; }
        public Nullable<int> UseFlag { get; set; }
        public Nullable<byte> SendRank { get; set; }
        public Nullable<int> Send_Num { get; set; }
        public Nullable<bool> st { get; set; }
        public Nullable<bool> Stop_Flag { get; set; }
    }
}
