//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideSm
    {
        public int ID { get; set; }
        public string Tel { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> SendInt { get; set; }
        public string Mid { get; set; }
        public string SMSTitle { get; set; }
        public Nullable<byte> Recheck { get; set; }
        public Nullable<int> UseFlag { get; set; }
        public Nullable<byte> SendRank { get; set; }
        public Nullable<int> Send_Num { get; set; }
        public Nullable<bool> st { get; set; }
        public Nullable<bool> Stop_Flag { get; set; }
    }
}
