//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsProduct
    {
        public int ProductId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<decimal> ProductSum { get; set; }
        public string Format { get; set; }
        public Nullable<byte> ProductKind { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<byte> XianFlag { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<byte> IsXH { get; set; }
        public string SName { get; set; }
        public string TaxIncluded { get; set; }
        public bool IsWeixinVisible { get; set; }
        public string spec { get; set; }
        public string comment { get; set; }
        public string parentName { get; set; }
    }
}
