//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsProduct
    {
        public int ProductId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductNum { get; set; }
        public Nullable<decimal> ProductSum { get; set; }
        public string Format { get; set; }
        public Nullable<byte> ProductKind { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> AttributeID { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<byte> XianFlag { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<byte> IsXH { get; set; }
        public string SName { get; set; }
        public string TaxIncluded { get; set; }
        public bool IsWeixinVisible { get; set; }
    }
}
