//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetalSmsSendEntities : DbContext
    {
        public MetalSmsSendEntities()
            : base("name=MetalSmsSendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Weixin_Log> Weixin_Log { get; set; }
        public DbSet<App_Log> App_Log { get; set; }
        public DbSet<ProvideSm> ProvideSms { get; set; }
        public DbSet<app_sms> app_sms { get; set; }
    }
}
