//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public Supply()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int ID { get; set; }
        public bool SupplyType { get; set; }
        public int CatalogID { get; set; }
        public string Product { get; set; }
        public string Quantity { get; set; }
        public string Mobile { get; set; }
        public string Contact { get; set; }
        public string Description { get; set; }
        public bool DeliveryType { get; set; }
        public int ProviceID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> isChecked { get; set; }
        public string Creater { get; set; }
        public string Price { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
