//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShtxSms2008Entities : DbContext
    {
        public ShtxSms2008Entities()
            : base("name=ShtxSms2008Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerBase> CustomerBases { get; set; }
        public DbSet<CustomerExtend> CustomerExtend { get; set; }
        public DbSet<Market> Markets { get; set; }
        public DbSet<XHMarketGroup> XHMarketGroups { get; set; }
        public DbSet<weixin_user> weixin_user { get; set; }
        public DbSet<Gp> Gps { get; set; }
        public DbSet<Price> Prices { get; set; }
        public DbSet<SmsProduct> SmsProducts { get; set; }
        public DbSet<Weixin_Pinglun> Weixin_Pinglun { get; set; }
        public DbSet<AppCustomerToken> AppCustomerTokens { get; set; }
        public DbSet<CataLog> CataLogs { get; set; }
        public DbSet<Channel> Channels { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<App_user> App_user { get; set; }
        public DbSet<SmsRole> SmsRoles { get; set; }
        public DbSet<ApkDownload> ApkDownloads { get; set; }
        public DbSet<MyAppGroup> MyAppGroups { get; set; }
        public DbSet<Supply> Supplies { get; set; }
    }
}
