//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weixin_Log
    {
        public int Id { get; set; }
        public string ErrCode { get; set; }
        public string ErrMsg { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Msg { get; set; }
        public string To { get; set; }
    }
}
