//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class weixin_user
    {
        public int Id { get; set; }
        public string OpenId { get; set; }
        public System.DateTime SubDate { get; set; }
        public int Type { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> BindDate { get; set; }
    }
}
