//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weixin_Pinglun
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> create { get; set; }
        public string mid { get; set; }
        public string icon { get; set; }
    }
}
